//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningASPMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public System.Guid Cno { get; set; }
        public string Cname { get; set; }
        public string Cpno { get; set; }
        public string Ccredit { get; set; }
    }
}
